# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e990917682eb79b8718032aa1f3696c533f3f93d57b3e650fdf89fdddcfa0199fa8039e1325e54ab305d9b075458a0df8a795c542da9a2f3a2858327d52baa95

test:
  secret_key_base: 8a93291bea21aa37afdea5b546ffc595482275982142106254e28ff0dee73e4e746b8874d6283c518318dfcca0b759a2850509d5e6bb70f3f2400a2d971caf37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
